spring.application.name=RopaStore

spring.datasource.url=jdbc:h2:mem:ropadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar la consola web de H2
spring.h2.console.enabled=true

# Actualizar automáticamente las tablas al iniciar
spring.jpa.hibernate.ddl-auto=update

# Info de Actuator
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=RopaStore
info.app.description=Aplicación de catálogo de tienda de ropa
